/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Estudiante;
import objetos.LeerObjetos;

/**
 *
 * @author edush
 */
public class vistaEstudiante extends javax.swing.JFrame{

    /**
     * Creates new form vistaEstudiante
     */
    public vistaEstudiante() {
        initComponents();
    }
    
    // variables globales
    String rutaArchivo = "C:\\Users\\edush\\OneDrive\\Escritorio\\salida.bin";
    ArrayList<Estudiante> listaEstudiantes = new ArrayList<Estudiante>();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNombres = new javax.swing.JTextField();
        tApellidos = new javax.swing.JTextField();
        tCarnet = new javax.swing.JTextField();
        bGuardar = new javax.swing.JButton();
        bLeerBinario = new javax.swing.JButton();
        cargaMasiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Carnet");

        bGuardar.setText("Guardar en archivo");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bLeerBinario.setText("Leer archivo");
        bLeerBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLeerBinarioActionPerformed(evt);
            }
        });

        cargaMasiva.setText("CARGA MASIVA");
        cargaMasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaMasivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tApellidos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(tCarnet))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(bGuardar)
                        .addGap(64, 64, 64)
                        .addComponent(bLeerBinario)))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cargaMasiva)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bLeerBinario))
                .addGap(64, 64, 64)
                .addComponent(cargaMasiva)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // IOException para excepciones de manejo de archivos
    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try {
            agregarNuevoEstudiante();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bLeerBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLeerBinarioActionPerformed
        // TODO add your handling code here:
        LeerObjetos lo = new LeerObjetos();
        lo.lecturaYmostrar();
    }//GEN-LAST:event_bLeerBinarioActionPerformed

    private void cargaMasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaMasivaActionPerformed
        try {
            // TODO add your handling code here:
            leerCSV();
        } catch (IOException ex) {
            Logger.getLogger(vistaEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargaMasivaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            }
            
        // IOException para excepciones de manejo de archivos
        private void agregarNuevoEstudiante() throws IOException{
            Estudiante temporal = new Estudiante();
            temporal.setNombres(tNombres.getText());
            temporal.setApellidos(tApellidos.getText());
            temporal.setCarnet(parseInt(tCarnet.getText()));
            
            if(listaEstudiantes.size()<300)
                listaEstudiantes.add(temporal);
            else
                JOptionPane.showMessageDialog(this, "Capacidad de estudiantes alcanzada. Max 300");
            
            
            
            guardarlistadoEstuadiantesArchivo();
        }
        
        
        public void leerCSV() throws FileNotFoundException, IOException{
            FileReader archivoEntrada = new FileReader("C:\\Users\\edush\\OneDrive\\Escritorio\\archivo.csv");
            BufferedReader lectura = new BufferedReader(archivoEntrada);
            String linea = lectura.readLine();
            int fila=0;
            
           while(linea!=null){
               
               if(fila>0){
                //System.out.println(linea);
                String[] campos = linea.split(",",3);
                    if(listaEstudiantes.size()<=300)
                    listaEstudiantes.add(new Estudiante(campos[0], parseInt(campos[1]), campos[2]));
                    else
                    JOptionPane.showMessageDialog(this, "Capacidad de estudiantes alcanzada Max 300");
               }
               fila++;
               linea=lectura.readLine();
           } 
           
           try {
                FileOutputStream archivoSalida = new FileOutputStream(rutaArchivo);                                
                ObjectOutputStream salida = new ObjectOutputStream(archivoSalida);                
                salida.writeObject(listaEstudiantes);
                //salida.close();
                archivoSalida.close();
            } catch (FileNotFoundException ex) {
                System.out.println("Ocurrio un error");
            }
            JOptionPane.showMessageDialog(this, "Carga masiva de estudiantes exitosa");
            
        }
    
        private void guardarlistadoEstuadiantesArchivo() throws IOException {             
                      
            try {
                
                
                FileOutputStream archivoSalida = new FileOutputStream(rutaArchivo);                                
                ObjectOutputStream salida = new ObjectOutputStream(archivoSalida);                
                salida.writeObject(listaEstudiantes);
                //salida.close();
                archivoSalida.close();
            } catch (FileNotFoundException ex) {
                System.out.println("Ocurrio un error");
            }
            JOptionPane.showMessageDialog(this, "Estudiante agregado exitosamente");
            
            tNombres.setText("");
            tApellidos.setText("");
            tCarnet.setText("");            
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLeerBinario;
    private javax.swing.JButton cargaMasiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tCarnet;
    private javax.swing.JTextField tNombres;
    // End of variables declaration//GEN-END:variables
}
